// Order From User
export const ORDER_FROM_USER_REQUEST='ORDER_FROM_USER_REQUEST';
export const ORDER_FROM_USER_SUCCESS='ORDER_FROM_USER_SUCCESS';
export const ORDER_FROM_USER_FAIL='ORDER_FROM_USER_FAIL';

// SignIn
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

// Logout
export const LOGOUT_USER = 'LOGOUT_USER'

// order deliver
export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'

//order detail
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

//shops
export const SHOPS_GET_REQUEST = 'SHOPS_GET_REQUEST'
export const SHOPS_GET_SUCCESS = 'SHOPS_GET_SUCCESS'
export const SHOPS_GET_FAIL = 'SHOPS_GET_FAIL'
//shop product
export const SHOP_PRODUCT_REQUEST = 'SHOPS_PRODUCT_REQUEST'
export const SHOP_PRODUCT_SUCCESS = 'SHOP_PRODUCT_SUCCESS'
export const SHOP_PRODUCT_FAIL = 'SHOP_PRODUCT_FAIL'
//send shop
export const ORDER_SHOP_REQUEST = 'ORDER_SHOP_REQUEST'
export const ORDER_SHOP_SUCCESS = 'ORDER_SHOP_SUCCESS'
export const ORDER_SHOP_FAIL = 'ORDER_SHOP_FAIL'
